# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this


input {
  kb_options = altwin:menu_win
}

device {
  name = logitech-wireless-mouse-mx-master-1
  scroll_factor = 0.8
}

misc {
  mouse_move_enables_dpms = false
  key_press_enables_dpms = true
}

