
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Prevent maximize for browsers to fix fullscreen exit behavior
# This stops browsers from going to maximized state when exiting video fullscreen
windowrule = maximize off, match:class .*
