# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ #

# استيراد ألوان Wallust التي يتم توليدها لـ JaKooLit
include ./kitty-themes/01-Wallust.conf

# استيراد الـ sequences للتحديث الفوري (بمجرد توفره)
include ~/.cache/wallust/sequences

# باقي إعداداتك (الخط، الشفافية، إلخ)
font_family FantasqueSansM Nerd Font Mono Bold
font_size 16.0
background_opacity 0.9
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 0

linux_display_server wayland

# Performance tuning
repaint_delay 10
input_delay 3
sync_to_monitor yes

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no
window_padding_width 4



# 3. حذف أو تعليق الألوان الثابتة لكي لا تمنع التغيير
# selection_foreground none
# selection_background none
# foreground #dddddd
# background #000000
# cursor #dddddd
