# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131313)
$foreground = rgb(DCDBDB)
$color0 = rgb(3B3B3B)
$color1 = rgb(131411)
$color2 = rgb(6A1112)
$color3 = rgb(373C22)
$color4 = rgb(5B6334)
$color5 = rgb(606936)
$color6 = rgb(757271)
$color7 = rgb(C5C3C3)
$color8 = rgb(8A8988)
$color9 = rgb(1A1B16)
$color10 = rgb(8D1618)
$color11 = rgb(49502D)
$color12 = rgb(798445)
$color13 = rgb(808C48)
$color14 = rgb(9C9897)
$color15 = rgb(C5C3C3)
