# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(18161D)
$foreground = rgb(D7A8F4)
$color0 = rgb(3F3D45)
$color1 = rgb(100D28)
$color2 = rgb(260B48)
$color3 = rgb(403A6C)
$color4 = rgb(6306A0)
$color5 = rgb(6905A8)
$color6 = rgb(6905A8)
$color7 = rgb(BD7BE7)
$color8 = rgb(8456A2)
$color9 = rgb(151235)
$color10 = rgb(330F60)
$color11 = rgb(554E90)
$color12 = rgb(8508D5)
$color13 = rgb(8C07E0)
$color14 = rgb(8C07E0)
$color15 = rgb(BD7BE7)
