# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(221B1A)
$foreground = rgb(FCE0B3)
$color0 = rgb(494140)
$color1 = rgb(280F0B)
$color2 = rgb(2D100A)
$color3 = rgb(662407)
$color4 = rgb(742906)
$color5 = rgb(A44605)
$color6 = rgb(B97D1C)
$color7 = rgb(F3CB8A)
$color8 = rgb(AA8E61)
$color9 = rgb(36140E)
$color10 = rgb(3C160E)
$color11 = rgb(883009)
$color12 = rgb(9B3708)
$color13 = rgb(DB5E07)
$color14 = rgb(F7A726)
$color15 = rgb(F3CB8A)
