# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-btop */
# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="{{foreground}}"

# Title color for boxes
theme[title]="{{foreground}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{color4}}"

# Background color of selected item in processes box
theme[selected_bg]="{{color2}}"

# Foreground color of selected item in processes box
theme[selected_fg]="{{background}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{color8}}"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="{{color6}}"

# Background color of the percentage meters
theme[meter_bg]="{{color0}}"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{color2}}"

# Cpu box outline color
theme[cpu_box]="{{color5}}"

# Memory/disks box outline color
theme[mem_box]="{{color2}}"

# Net up/down box outline color
theme[net_box]="{{color4}}"

# Processes box outline color
theme[proc_box]="{{color6}}"

# Box divider line and small boxes line color
theme[div_line]="{{color8}}"

# Temperature graph colors
theme[temp_start]="{{color4}}"
theme[temp_mid]="{{color3}}"
theme[temp_end]="{{color1}}"

# CPU graph colors
theme[cpu_start]="{{color4}}"
theme[cpu_mid]="{{color3}}"
theme[cpu_end]="{{color1}}"

# Mem/Disk free meter
theme[free_start]="{{color6}}"
theme[free_mid]="{{color6}}"
theme[free_end]="{{color2}}"

# Mem/Disk cached meter
theme[cached_start]="{{color4}}"
theme[cached_mid]="{{color4}}"
theme[cached_end]="{{color4}}"

# Mem/Disk available meter
theme[available_start]="{{color5}}"
theme[available_mid]="{{color5}}"
theme[available_end]="{{color5}}"

# Mem/Disk used meter
theme[used_start]="{{color1}}"
theme[used_mid]="{{color1}}"
theme[used_end]="{{color1}}"

# Download graph colors
theme[download_start]="{{color4}}"
theme[download_mid]="{{color4}}"
theme[download_end]="{{color6}}"

# Upload graph colors
theme[upload_start]="{{color5}}"
theme[upload_mid]="{{color5}}"
theme[upload_end]="{{color1}}"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="{{color4}}"
theme[process_mid]="{{color3}}"
theme[process_end]="{{color1}}"
