# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C8E7CC
background         #1B1D1D
cursor             #7D9F85

active_tab_foreground     #1B1D1D
active_tab_background     #C8E7CC
inactive_tab_foreground   #C8E7CC
inactive_tab_background   #1B1D1D

active_border_color   #C8E7CC
inactive_border_color #1B1D1D
bell_border_color     #141E1C

color0      #424344
color1		#141E1C
color2		#26422E
color3		#355C3D
color4		#355C3D
color5		#3B6E44
color6		#498B53
color7		#A8D4AE
color8		#75947A
color9		#1B2825
color10		#32583D
color11		#477A51
color12		#477A51
color13		#4E925B
color14		#61B96E
color15		#A8D4AE
