# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FED9B0
background         #191516
cursor             #B68160

active_tab_foreground     #191516
active_tab_background     #FED9B0
inactive_tab_foreground   #FED9B0
inactive_tab_background   #191516

active_border_color   #FED9B0
inactive_border_color #191516
bell_border_color     #521F0D

color0      #413C3C
color1		#521F0D
color2		#531F0D
color3		#531F0D
color4		#9B3E0D
color5		#9B3E0D
color6		#BD6D15
color7		#F5C085
color8		#AC865D
color9		#6E2911
color10		#6E2911
color11		#6E2911
color12		#CE5211
color13		#CE5211
color14		#FC911C
color15		#F5C085
