# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D7A8F4
background         #18161D
cursor             #855CAA

active_tab_foreground     #18161D
active_tab_background     #D7A8F4
inactive_tab_foreground   #D7A8F4
inactive_tab_background   #18161D

active_border_color   #D7A8F4
inactive_border_color #18161D
bell_border_color     #100D28

color0      #3F3D45
color1		#100D28
color2		#260B48
color3		#403A6C
color4		#6306A0
color5		#6905A8
color6		#6905A8
color7		#BD7BE7
color8		#8456A2
color9		#151235
color10		#330F60
color11		#554E90
color12		#8508D5
color13		#8C07E0
color14		#8C07E0
color15		#BD7BE7
