# Semicolon RGB values for true color escape sequences
primary_rgb="156,153,149"
primary_rgb="${primary_rgb//,/;}"

secondary_rgb="173,164,147"
secondary_rgb="${secondary_rgb//,/;}"

accent_rgb="240,206,139"
accent_rgb="${accent_rgb//,/;}"

error_rgb="93,89,74"
error_rgb="${error_rgb//,/;}"

fg_rgb="255,246,230"
fg_rgb="${fg_rgb//,/;}"

green_rgb="150,70,41"
green_rgb="${green_rgb//,/;}"

# Set the yt-x interface colors
THEME_FZF_ICON_COLOR_PRIMARY="$(printf "\033[38;2;${primary_rgb}m")"
THEME_FZF_ICON_COLOR_SECONDARY="$(printf "\033[38;2;${secondary_rgb}m")"
THEME_FZF_ICON_COLOR_ACCENT="$(printf "\033[38;2;${accent_rgb}m")"
THEME_FZF_ICON_COLOR_ERROR="$(printf "\033[38;2;${error_rgb}m")"
THEME_FZF_PREVIEW_TITLE="$(printf "\033[38;2;${fg_rgb}m")"
THEME_FZF_PREVIEW_KEY="$(printf "\033[38;2;${primary_rgb}m")"
THEME_FZF_PREVIEW_VALUE="$(printf "\033[38;2;${fg_rgb}m")"
THEME_FZF_PREVIEW_DIVIDER="$(printf "\033[38;2;${secondary_rgb}m")"
THEME_PLAYER_START="$(printf "\033[38;2;${green_rgb}m")"

# Override FZF options by appending color overrides
CONFIG_FZF_OPTS="$CONFIG_FZF_OPTS \
  --color=bg+:#454748 \
  --color=bg:#1F2121 \
  --color=border:#9C9995 \
  --color=fg:#FFF6E6 \
  --color=gutter:#1F2121 \
  --color=header:#9C9995 \
  --color=hl+:#9C9995 \
  --color=hl:#9C9995 \
  --color=info:#ADA493 \
  --color=marker:#F0CE8B \
  --color=pointer:#F0CE8B \
  --color=prompt:#9C9995 \
  --color=query:#FFF6E6:regular \
  --color=scrollbar:#9C9995 \
  --color=separator:#F0CE8B \
  --color=spinner:#F0CE8B"

# Override Gum options
CONFIG_GUM_FILTER_OPTS="--prompt.foreground #9C9995 --indicator.foreground #9C9995 --selected-indicator.foreground #9C9995 --unselected-prefix.foreground #ADA493 --header.foreground #9C9995 --text.foreground #FFF6E6 --cursor-text.foreground #FFF6E6 --match.foreground #9C9995 --placeholder.foreground #ADA493 --prompt > --indicator ◆ --selected-prefix ◉ --unselected-prefix ○ --placeholder こんにちは..."
CONFIG_GUM_OPTS="$CONFIG_GUM_FILTER_OPTS"
CONFIG_GUM_INPUT_OPTS="--prompt.foreground #9C9995 --cursor.foreground #FFF6E6 --placeholder こんにちは... --cursor.mode blink"
CONFIG_GUM_PAGER_OPTS="--foreground #FFF6E6 --line-number.foreground #ADA493 --match.foreground #9C9995 --match-highlight.foreground #1F2121 --match-highlight.background #9C9995 --help.foreground #ADA493 --show-line-numbers --soft-wrap --border-foreground #9C9995"
CONFIG_GUM_SPIN_OPTS="--spinner dot --spinner.foreground #9C9995 --title.foreground #ADA493 --align left"
CONFIG_GUM_CONFIRM_OPTS="--prompt.foreground #9C9995 --selected.foreground #1F2121 --selected.background #9C9995 --unselected.foreground #ADA493"
