# Semicolon RGB values for true color escape sequences
primary_rgb="121,140,182"
primary_rgb="${primary_rgb//,/;}"

secondary_rgb="165,133,108"
secondary_rgb="${secondary_rgb//,/;}"

accent_rgb="232,130,71"
accent_rgb="${accent_rgb//,/;}"

error_rgb="69,99,136"
error_rgb="${error_rgb//,/;}"

fg_rgb="247,215,190"
fg_rgb="${fg_rgb//,/;}"

green_rgb="161,78,59"
green_rgb="${green_rgb//,/;}"

# Set the yt-x interface colors
THEME_FZF_ICON_COLOR_PRIMARY="$(printf "\033[38;2;${primary_rgb}m")"
THEME_FZF_ICON_COLOR_SECONDARY="$(printf "\033[38;2;${secondary_rgb}m")"
THEME_FZF_ICON_COLOR_ACCENT="$(printf "\033[38;2;${accent_rgb}m")"
THEME_FZF_ICON_COLOR_ERROR="$(printf "\033[38;2;${error_rgb}m")"
THEME_FZF_PREVIEW_TITLE="$(printf "\033[38;2;${fg_rgb}m")"
THEME_FZF_PREVIEW_KEY="$(printf "\033[38;2;${primary_rgb}m")"
THEME_FZF_PREVIEW_VALUE="$(printf "\033[38;2;${fg_rgb}m")"
THEME_FZF_PREVIEW_DIVIDER="$(printf "\033[38;2;${secondary_rgb}m")"
THEME_PLAYER_START="$(printf "\033[38;2;${green_rgb}m")"

# Override FZF options by appending color overrides
CONFIG_FZF_OPTS="$CONFIG_FZF_OPTS \
  --color=bg+:#4E4E50 \
  --color=bg:#29282A \
  --color=border:#798CB6 \
  --color=fg:#F7D7BE \
  --color=gutter:#29282A \
  --color=header:#798CB6 \
  --color=hl+:#798CB6 \
  --color=hl:#798CB6 \
  --color=info:#A5856C \
  --color=marker:#E88247 \
  --color=pointer:#E88247 \
  --color=prompt:#798CB6 \
  --color=query:#F7D7BE:regular \
  --color=scrollbar:#798CB6 \
  --color=separator:#E88247 \
  --color=spinner:#E88247"

# Override Gum options
CONFIG_GUM_FILTER_OPTS="--prompt.foreground #798CB6 --indicator.foreground #798CB6 --selected-indicator.foreground #798CB6 --unselected-prefix.foreground #A5856C --header.foreground #798CB6 --text.foreground #F7D7BE --cursor-text.foreground #F7D7BE --match.foreground #798CB6 --placeholder.foreground #A5856C --prompt > --indicator ◆ --selected-prefix ◉ --unselected-prefix ○ --placeholder こんにちは..."
CONFIG_GUM_OPTS="$CONFIG_GUM_FILTER_OPTS"
CONFIG_GUM_INPUT_OPTS="--prompt.foreground #798CB6 --cursor.foreground #F7D7BE --placeholder こんにちは... --cursor.mode blink"
CONFIG_GUM_PAGER_OPTS="--foreground #F7D7BE --line-number.foreground #A5856C --match.foreground #798CB6 --match-highlight.foreground #29282A --match-highlight.background #798CB6 --help.foreground #A5856C --show-line-numbers --soft-wrap --border-foreground #798CB6"
CONFIG_GUM_SPIN_OPTS="--spinner dot --spinner.foreground #798CB6 --title.foreground #A5856C --align left"
CONFIG_GUM_CONFIRM_OPTS="--prompt.foreground #798CB6 --selected.foreground #29282A --selected.background #798CB6 --unselected.foreground #A5856C"
